### ISSUE TITLE
como que abre

### ISSUE THREAD

**Issue by Bebel132** [Kisrym/Notepad#1]
cpmo que abre

**Comment by Kisrym** [comment]
Você precisa ter instalado o Python e o PyQt5

## Instalando Python
Você pode instalar o Python no próprio site oficial deles: https://www.python.org
No projeto, foi utilizado o Python 3.9.6, entretanto você pode usar qualquer versão acima desta.

## Instalando libs
Com o Python instalado, você colará o seguinte comando no terminal
`
pip install PyQt5
`
## Rodando o programa
Quando tiver feito os dois passos anteriores, basta dar double-click no arquivo `main.py` ou usando o comando `python main.py` no diretório do arquivo.

**Comment by Bebel132** [comment]
Brabokk
